services:
  db:
    container_name: ukhsa-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: UKHSA
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [CMD-SHELL, "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  update:
    container_name: ukhsa-update
    entrypoint: ["dotnet", "ef", "database", "update"]
    build:
      context: .
      dockerfile: ./docker/update/Dockerfile
    env_file:
      - docker/common.env
    depends_on:
      db:
        condition: service_healthy
    profiles: [update]
  app-dev:
    container_name: ukhsa-app-dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - docker/common.env
    volumes:
      - ./App:/UKHSA/App
      - aspnet_keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      db:
        condition: service_healthy
        restart: true
    profiles: ["", dev]
  app-prod:
    container_name: ukhsa-app-prod
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - docker/common.env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - aspnet_keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      db:
        condition: service_healthy
        restart: true
    profiles: [prod]
volumes:
  postgres_data:
  aspnet_keys:
