services:
  db:
    container_name: ukhsa-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: UKHSA
      ASPNET_ENVIRONMENT: Development
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: ukhsa-app
    build: .
    ports:
      - 8080:8080
      - 5272:5272
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=UKHSA;Username=postgres;Password=${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
        restart: true
volumes:
  postgres_data:
